import { readFile, writeFile } from "node:fs/promises"
import { deflateSync } from "node:zlib"
import { createHash } from "node:crypto"

// Convert the unmodified Liberation Sans 2.1.5 TTF into lossless WOFF data.
// Source: https://github.com/liberationfonts/liberation-fonts/releases/tag/2.1.5
// Usage: bun scripts/embed-note-font.ts /path/to/LiberationSans-Regular.ttf
const path = process.argv[2]
if (!path) throw new Error("Expected LiberationSans-Regular.ttf path")
const ttf = await readFile(path)
const count = ttf.readUInt16BE(4)
let offset = 44 + count * 20
let sfntSize = 12 + count * 16
const tables = Array.from({ length: count }, (_, i) => {
  const entry = 12 + i * 16
  const length = ttf.readUInt32BE(entry + 12)
  const start = ttf.readUInt32BE(entry + 8)
  const original = ttf.subarray(start, start + length)
  const compressed = deflateSync(original)
  const data = compressed.length < length ? compressed : original
  const table = {
    tag: ttf.readUInt32BE(entry),
    checksum: ttf.readUInt32BE(entry + 4),
    length,
    offset,
    data,
  }
  offset += (data.length + 3) & ~3
  sfntSize += (length + 3) & ~3
  return table
})
const woff = Buffer.alloc(offset)
woff.writeUInt32BE(0x774f4646, 0)
woff.writeUInt32BE(ttf.readUInt32BE(0), 4)
woff.writeUInt32BE(woff.length, 8)
woff.writeUInt16BE(count, 12)
woff.writeUInt32BE(sfntSize, 16)
woff.writeUInt16BE(2, 20)
woff.writeUInt16BE(1, 22)
for (const [i, table] of tables.entries()) {
  const entry = 44 + i * 20
  woff.writeUInt32BE(table.tag, entry)
  woff.writeUInt32BE(table.offset, entry + 4)
  woff.writeUInt32BE(table.data.length, entry + 8)
  woff.writeUInt32BE(table.length, entry + 12)
  woff.writeUInt32BE(table.checksum, entry + 16)
  table.data.copy(woff, table.offset)
}
await writeFile(
  new URL("../lib/text/note-font-data.ts", import.meta.url),
  `// Generated by scripts/embed-note-font.ts; do not edit.\n// Liberation Sans 2.1.5, SIL Open Font License; see LICENSE.Liberation.\n// Original TTF SHA-256: ${createHash("sha256").update(ttf).digest("hex")}\nexport const noteFontData = "${woff.toString("base64")}"\n`,
)
